version: '2.4'
services:

  service-0:
    image: encoredtechr/deepo:keras-py36-r
    ports:
      - 8880:8888
      - 6000:6006
      - 8780:8787
    environment:
      - JUPYTER_PASSWD=${JUPYTER_PASSWD}
      - NVIDIA_VISIBLE_DEVICES=0
    volumes:
      - ./jupyter-config:/root/.jupyter
    runtime: nvidia
    command: /init jupyter notebook

  service-1:
    image: encoredtechr/deepo:keras-py36-r
    ports:
      - 8881:8888
      - 6001:6006
      - 8781:8787
    environment:
      - JUPYTER_PASSWD=${JUPYTER_PASSWD}
      - NVIDIA_VISIBLE_DEVICES=1
    volumes:
      - ./jupyter-config:/root/.jupyter
    runtime: nvidia
    command: /init jupyter notebook

  service-2:
    image: encoredtechr/deepo:keras-py36-r
    ports:
      - 8882:8888
      - 6002:6006
      - 8782:8787
    environment:
      - JUPYTER_PASSWD=${JUPYTER_PASSWD}
      - NVIDIA_VISIBLE_DEVICES=2
    volumes:
      - ./jupyter-config:/root/.jupyter
    runtime: nvidia
    command: /init jupyter notebook

  service-3:
    image: encoredtechr/deepo:keras-py36-r
    ports:
      - 8883:8888
      - 6003:6006
      - 8783:8787
    environment:
      - JUPYTER_PASSWD=${JUPYTER_PASSWD}
      - NVIDIA_VISIBLE_DEVICES=3
    volumes:
      - ./jupyter-config:/root/.jupyter
    runtime: nvidia
    command: /init jupyter notebook

